plugins {
    id 'multiloader-loader'
    id 'naturalist-publish'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    localRuntime "dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime:${lambdynamiclights}"

    compileOnly "maven.modrinth:field-guide:${field_guide_fabric}"

    localRuntime "maven.modrinth:immersive-overlays:${immersive_overlays_fabric}"
    localRuntime "maven.modrinth:not-enough-animations:${nea_fabric}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('run')
        }
    }
}

publishMods {
    file = jar.archiveFile
    version = "${mod_version}+${minecraft_version}-fabric"
    modLoaders.add('fabric')
    displayName = "${mod_name} ${mod_version} (Fabric ${minecraft_version})"
    curseforge { requires('fabric-api') }
    modrinth { requires('fabric-api') }
}

applyLoaderAttribute('fabric', ['apiElements', 'runtimeElements', 'sourcesElements', 'includeInternal', 'modCompileClasspath'])
