plugins {
    id 'multiloader-loader'
    id 'naturalist-publish'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neo_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = project.file('run')
        }
        server {
            server()
            gameDirectory = project.file('run/server')
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

sourceSets.main.java.exclude 'com/crispytwig/naturalist/datagen/**'

dependencies {
    compileOnly "maven.modrinth:field-guide:${field_guide_neoforge}"
    runtimeOnly "maven.modrinth:field-guide:${field_guide_neoforge}"

    runtimeOnly "maven.modrinth:immersive-overlays:${immersive_overlays}-neoforge"
}

publishMods {
    file = jar.archiveFile
    version = "${mod_version}+${minecraft_version}-neoforge"
    modLoaders.add('neoforge')
    displayName = "${mod_name} ${mod_version} (NeoForge ${minecraft_version})"
}

applyLoaderAttribute('neoforge', ['apiElements', 'runtimeElements', 'sourcesElements'], ['jarJar'])
