package com.crispytwig.naturalist.tags;

import com.crispytwig.naturalist.Naturalist;
import net.minecraft.core.registries.Registries;
import net.minecraft.tags.TagKey;
import net.minecraft.world.level.biome.Biome;
import org.jetbrains.annotations.NotNull;

@SuppressWarnings("unused")
public class NaturalistBiomeTags {
    public static final TagKey<Biome> HAS_ALLIGATOR = tag("has_alligator");
    public static final TagKey<Biome> HAS_ANGLERFISH = tag("has_anglerfish");
    public static final TagKey<Biome> HAS_RAY = tag("has_ray");
    public static final TagKey<Biome> HAS_BLOBFISH = tag("has_blobfish");
    public static final TagKey<Biome> HAS_PIRANHA = tag("has_piranha");
    public static final TagKey<Biome> HAS_BASS = tag("has_bass");
    public static final TagKey<Biome> HAS_BEAR = tag("has_bear");
    public static final TagKey<Biome> HAS_BLACK_BEAR = tag("has_black_bear");
    public static final TagKey<Biome> HAS_BLUEJAY = tag("has_bluejay");
    public static final TagKey<Biome> HAS_BOAR = tag("has_boar");
    public static final TagKey<Biome> HAS_BUTTERFLY = tag("has_butterfly");
    public static final TagKey<Biome> HAS_CANARY = tag("has_canary");
    public static final TagKey<Biome> HAS_CARDINAL = tag("has_cardinal");
    public static final TagKey<Biome> HAS_CATFISH = tag("has_catfish");
    public static final TagKey<Biome> HAS_CAPYBARA = tag("has_capybara");
    public static final TagKey<Biome> HAS_CLAM = tag("has_clam");
    public static final TagKey<Biome> HAS_CORAL_SNAKE = tag("has_coral_snake");
    public static final TagKey<Biome> HAS_CRAB = tag("has_crab");
    public static final TagKey<Biome> HAS_DEER = tag("has_deer");
    public static final TagKey<Biome> HAS_DESERT_SCORPION = tag("has_desert_scorpion");
    public static final TagKey<Biome> HAS_DRAGONFLY = tag("has_dragonfly");
    public static final TagKey<Biome> HAS_DUCK = tag("has_duck");
    public static final TagKey<Biome> HAS_ELEPHANT = tag("has_elephant");
    public static final TagKey<Biome> HAS_FINCH = tag("has_finch");
    public static final TagKey<Biome> HAS_FIREFLY = tag("has_firefly");
    public static final TagKey<Biome> HAS_GIANT_ISOPOD = tag("has_giant_isopod");
    public static final TagKey<Biome> HAS_HEDGEHOG = tag("has_hedgehog");
    public static final TagKey<Biome> HAS_GIRAFFE = tag("has_giraffe");
    public static final TagKey<Biome> HAS_GREAT_WHITE_SHARK = tag("has_great_white_shark");
    public static final TagKey<Biome> HAS_HIPPO = tag("has_hippo");
    public static final TagKey<Biome> HAS_JELLYFISH = tag("has_jellyfish");
    public static final TagKey<Biome> HAS_JUNGLE_SCORPION = tag("has_jungle_scorpion");
    public static final TagKey<Biome> HAS_KOMODO_DRAGON = tag("has_komodo_dragon");
    public static final TagKey<Biome> HAS_LION = tag("has_lion");
    public static final TagKey<Biome> HAS_LIZARD = tag("has_lizard");
    public static final TagKey<Biome> HAS_MAMMOTH = tag("has_mammoth");
    public static final TagKey<Biome> HAS_MOLE = tag("has_mole");
    public static final TagKey<Biome> HAS_OSTRICH = tag("has_ostrich");
    public static final TagKey<Biome> HAS_RAT = tag("has_rat");
    public static final TagKey<Biome> HAS_RATTLESNAKE = tag("has_rattlesnake");
    public static final TagKey<Biome> HAS_RHINO = tag("has_rhino");
    public static final TagKey<Biome> HAS_ROBIN = tag("has_robin");
    public static final TagKey<Biome> HAS_SNAIL = tag("has_snail");
    public static final TagKey<Biome> HAS_SNAKE = tag("has_snake");
    public static final TagKey<Biome> HAS_SPARROW = tag("has_sparrow");
    public static final TagKey<Biome> HAS_STARFISH = tag("has_starfish");
    public static final TagKey<Biome> HAS_TIGER = tag("has_tiger");
    public static final TagKey<Biome> HAS_TORTOISE = tag("has_tortoise");
    public static final TagKey<Biome> HAS_TURKEY = tag("has_turkey");
    public static final TagKey<Biome> HAS_VULTURE = tag("has_vulture");
    public static final TagKey<Biome> HAS_ZEBRA = tag("has_zebra");
    public static final TagKey<Biome> HAS_WHALE = tag("has_whale");
    public static final TagKey<Biome> HAS_ANT_HILL = tag("has_ant_hill");

    public static final TagKey<Biome> BLACKLIST_ALLIGATOR = tag("blacklist/blacklist_alligator");
    public static final TagKey<Biome> BLACKLIST_ANGLERFISH = tag("blacklist/blacklist_anglerfish");
    public static final TagKey<Biome> BLACKLIST_RAY = tag("blacklist/blacklist_ray");
    public static final TagKey<Biome> BLACKLIST_BLOBFISH = tag("blacklist/blacklist_blobfish");
    public static final TagKey<Biome> BLACKLIST_PIRANHA = tag("blacklist/blacklist_piranha");
    public static final TagKey<Biome> BLACKLIST_BASS = tag("blacklist/blacklist_bass");
    public static final TagKey<Biome> BLACKLIST_BEAR = tag("blacklist/blacklist_bear");
    public static final TagKey<Biome> BLACKLIST_BLACK_BEAR = tag("blacklist/blacklist_black_bear");
    public static final TagKey<Biome> BLACKLIST_BLUEJAY = tag("blacklist/blacklist_bluejay");
    public static final TagKey<Biome> BLACKLIST_BOAR = tag("blacklist/blacklist_boar");
    public static final TagKey<Biome> BLACKLIST_BUTTERFLY = tag("blacklist/blacklist_butterfly");
    public static final TagKey<Biome> BLACKLIST_CANARY = tag("blacklist/blacklist_canary");
    public static final TagKey<Biome> BLACKLIST_CARDINAL = tag("blacklist/blacklist_cardinal");
    public static final TagKey<Biome> BLACKLIST_CAPYBARA = tag("blacklist/blacklist_capybara");
    public static final TagKey<Biome> BLACKLIST_CATFISH = tag("blacklist/blacklist_catfish");
    public static final TagKey<Biome> BLACKLIST_CLAM = tag("blacklist/blacklist_clam");
    public static final TagKey<Biome> BLACKLIST_CORAL_SNAKE = tag("blacklist/blacklist_coral_snake");
    public static final TagKey<Biome> BLACKLIST_CRAB = tag("blacklist/blacklist_crab");
    public static final TagKey<Biome> BLACKLIST_DEER = tag("blacklist/blacklist_deer");
    public static final TagKey<Biome> BLACKLIST_DESERT_SCORPION = tag("blacklist/blacklist_desert_scorpion");
    public static final TagKey<Biome> BLACKLIST_DRAGONFLY = tag("blacklist/blacklist_dragonfly");
    public static final TagKey<Biome> BLACKLIST_DUCK = tag("blacklist/blacklist_duck");
    public static final TagKey<Biome> BLACKLIST_ELEPHANT = tag("blacklist/blacklist_elephant");
    public static final TagKey<Biome> BLACKLIST_FINCH = tag("blacklist/blacklist_finch");
    public static final TagKey<Biome> BLACKLIST_FIREFLY = tag("blacklist/blacklist_firefly");
    public static final TagKey<Biome> BLACKLIST_GIANT_ISOPOD = tag("blacklist/blacklist_giant_isopod");
    public static final TagKey<Biome> BLACKLIST_HEDGEHOG = tag("blacklist/blacklist_hedgehog");
    public static final TagKey<Biome> BLACKLIST_GIRAFFE = tag("blacklist/blacklist_giraffe");
    public static final TagKey<Biome> BLACKLIST_GREAT_WHITE_SHARK = tag("blacklist/blacklist_great_white_shark");
    public static final TagKey<Biome> BLACKLIST_HIPPO = tag("blacklist/blacklist_hippo");
    public static final TagKey<Biome> BLACKLIST_JELLYFISH = tag("blacklist/blacklist_jellyfish");
    public static final TagKey<Biome> BLACKLIST_JUNGLE_SCORPION = tag("blacklist/blacklist_jungle_scorpion");
    public static final TagKey<Biome> BLACKLIST_KOMODO_DRAGON = tag("blacklist/blacklist_komodo_dragon");
    public static final TagKey<Biome> BLACKLIST_LION = tag("blacklist/blacklist_lion");
    public static final TagKey<Biome> BLACKLIST_LIZARD = tag("blacklist/blacklist_lizard");
    public static final TagKey<Biome> BLACKLIST_MAMMOTH = tag("blacklist/blacklist_mammoth");
    public static final TagKey<Biome> BLACKLIST_MOLE = tag("blacklist/blacklist_mole");
    public static final TagKey<Biome> BLACKLIST_OSTRICH = tag("blacklist/blacklist_ostrich");
    public static final TagKey<Biome> BLACKLIST_RAT = tag("blacklist/blacklist_rat");
    public static final TagKey<Biome> BLACKLIST_RATTLESNAKE = tag("blacklist/blacklist_rattlesnake");
    public static final TagKey<Biome> BLACKLIST_RHINO = tag("blacklist/blacklist_rhino");
    public static final TagKey<Biome> BLACKLIST_ROBIN = tag("blacklist/blacklist_robin");
    public static final TagKey<Biome> BLACKLIST_SNAIL = tag("blacklist/blacklist_snail");
    public static final TagKey<Biome> BLACKLIST_SNAKE = tag("blacklist/blacklist_snake");
    public static final TagKey<Biome> BLACKLIST_SPARROW = tag("blacklist/blacklist_sparrow");
    public static final TagKey<Biome> BLACKLIST_STARFISH = tag("blacklist/blacklist_starfish");
    public static final TagKey<Biome> BLACKLIST_TIGER = tag("blacklist/blacklist_tiger");
    public static final TagKey<Biome> BLACKLIST_TORTOISE = tag("blacklist/blacklist_tortoise");
    public static final TagKey<Biome> BLACKLIST_TURKEY = tag("blacklist/blacklist_turkey");
    public static final TagKey<Biome> BLACKLIST_VULTURE = tag("blacklist/blacklist_vulture");
    public static final TagKey<Biome> BLACKLIST_ZEBRA = tag("blacklist/blacklist_zebra");
    public static final TagKey<Biome> BLACKLIST_WHALE = tag("blacklist/blacklist_whale");
    public static final TagKey<Biome> BLACKLIST_FOREST_FOXES = tag("blacklist/blacklist_forest_foxes");
    public static final TagKey<Biome> BLACKLIST_FOREST_RABBITS = tag("blacklist/blacklist_forest_rabbits");

    private static @NotNull TagKey<Biome> tag(String name) {
        return TagKey.create(Registries.BIOME, Naturalist.location(name));
    }
}
